Fix the use of removed numpy types (#6495)
Both `np.bool` and `np.unicode` were [deprecated in numpy
1.20.0](https://numpy.org/doc/stable/release/1.20.0-notes.html#:~:text=Deprecations-,Using%20the%20aliases%20of%20builtin%20types,-like%20np.int%20is%20deprecated%23)
and [removed in numpy
1.24.0](https://numpy.org/doc/stable/release/1.24.0-notes.html#:~:text=The-,deprecation,-for%20the%20aliases).
Since [release notes of
1.20.0](https://numpy.org/doc/stable/release/1.20.0-notes.html#:~:text=Deprecations-,Using%20the%20aliases%20of%20builtin%20types,-like%20np.int%20is%20deprecated%23)
say that `np.bool` is identical to `bool` and `np.unicode` is identical
to `str`, I changed them that way.

Confirmed using numpy 1.23.5:
```
>>> np.__version__
'1.23.5'
>>> np.unicode is str
<stdin>:1: DeprecationWarning: `np.unicode` is a deprecated alias for `np.compat.unicode`. To silence this warning, use `np.compat.unicode` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `str` for which `np.compat.unicode` is itself an alias. Doing this will not modify any behaviour and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
True
>>> np.bool is bool
<stdin>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
True
```
In numpy 1.24.0 both types don't exist anymore:
```
>>> np.__version__
'1.24.0'
>>> np.unicode       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'unicode'
>>> np.bool
<stdin>:1: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
```